// Builds crawler/internal/vocab/us.tsv: the makes and models the title-only
// sources (Craigslist, Marketplace) match ad titles against when the local
// database has no structured source (AutoHebdo) to learn them from.
//
//   node tools/us-vocabulary/generate.mjs > crawler/internal/vocab/us.tsv
//
// Source: NHTSA vPIC (public, no key), cars + SUVs/vans + pickups only, so
// motorcycles and ATVs stay out. One request per make and vehicle type,
// 300 ms apart.
const MAKES = [
  'Acura', 'Alfa Romeo', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Fiat',
  'Ford', 'Genesis', 'GMC', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Kia', 'Land Rover',
  'Lexus', 'Lincoln', 'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan', 'Porsche', 'Ram',
  'Subaru', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo', 'Scion', 'Pontiac', 'Saturn', 'Mercury',
];
const TYPES = ['car', 'multipurpose passenger vehicle (mpv)', 'truck'];

// Model names that are also ordinary listing words: matching them alone
// would label any ad that says "sport" or "limited".
const STOP = new Set([
  'sport', 'limited', 'touring', 'classic', 'custom', 'base', 'deluxe', 'special', 'standard',
  'coupe', 'sedan', 'wagon', 'van', 'truck', 'pickup', 'convertible', 'hybrid', 'electric',
  'new', 'unknown', 'other', 'chassis', 'cab', 'club', 'crew', 'cargo', 'express', 'city',
]);

// Heavy trucks and chassis cabs: not what a used-car buyer is pricing.
const HEAVY = /\b(?:[fe]-?[4-9]\d0|[4-9]500|chassis|cutaway|stripped|incomplete|motor ?home|school bus)\b/i;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const models = new Map(); // "make\tmodel" -> true

for (const make of MAKES) {
  for (const type of TYPES) {
    const url = `https://vpic.nhtsa.dot.gov/api/vehicles/GetModelsForMakeYear/make/${encodeURIComponent(make)}` +
      `/vehicletype/${encodeURIComponent(type)}?format=json`;
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${make} ${type}: HTTP ${res.status}`);
    for (const r of (await res.json()).Results) {
      const model = String(r.Model_Name).trim();
      if (!model || STOP.has(model.toLowerCase()) || HEAVY.test(model)) continue;
      models.set(`${make}\t${model}`, true);
    }
    await sleep(300);
  }
}

console.log('# make\tmodel (generated by tools/us-vocabulary/generate.mjs from NHTSA vPIC; do not edit by hand)');
for (const key of [...models.keys()].sort()) console.log(key);
